version: '3'

services:
  ch_server:
    image: yandex/clickhouse-server
    ports:
      - '8123:8123'
    volumes:
      - ./db:/var/lib/clickhouse
      - ./datasets:/home/ch/datasets
    networks:
      - ch_network
  ch_client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
    networks:
      - ch_network
networks:
  ch_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.222.1.0/24
